# Generated by Django 6.0.6 on 2026-07-01 01:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaskedSentenceAudio',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('audio', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='RadicalSessionAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-finished_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SentenceSessionAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-finished_at', 'id'],
            },
        ),
    ]
