# Generated by Django 6.0.6 on 2026-07-01 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('practice_assessments', '0001_initial'),
        ('radical_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='radicalsessionassessment',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='radical_sessions.radicalsession'),
        ),
    ]
