# Generated by Django 6.0.6 on 2026-06-30 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('practice_assessments', '0002_initial'),
        ('sentence_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentencesessionassessment',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='sentence_sessions.sentencesession'),
        ),
    ]
