# Generated by Django 6.0.6 on 2026-07-01 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice_assessments', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MaskedSentenceAudio',
        ),
    ]
