# Generated by Django 6.0.6 on 2026-06-24 19:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Logogram',
            fields=[
                ('id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('occurrences', models.PositiveIntegerField(default=0)),
                ('pinyin', models.TextField(blank=True, default='')),
                ('meaning', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Radical',
            fields=[
                ('id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('pinyin', models.TextField(blank=True, default='')),
                ('meaning', models.TextField(blank=True, default='')),
                ('pronounce', models.CharField(blank=True, default='', max_length=512)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('value', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('value', models.TextField(blank=True, default='')),
                ('pos_tag', models.CharField(blank=True, default='', max_length=255)),
                ('occurrences', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RadicalSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('num_of_radicals', models.PositiveIntegerField(default=0)),
                ('highest_score', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RadicalSessionTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.PositiveIntegerField(default=0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='radicals.radicalsession')),
            ],
            options={
                'ordering': ['-finished_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RadicalLogogramMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logogram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radicals.logogram')),
                ('radical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radicals.radical')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('logogram', 'radical'), name='uniq_logogram_radical')],
            },
        ),
        migrations.CreateModel(
            name='RadicalSessionRadical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('radical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radicals.radical')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_radicals', to='radicals.radicalsession')),
            ],
            options={
                'ordering': ['session', 'position'],
                'constraints': [models.UniqueConstraint(fields=('session', 'radical'), name='uniq_session_radical'), models.UniqueConstraint(fields=('session', 'position'), name='uniq_session_position')],
            },
        ),
        migrations.CreateModel(
            name='RadicalSessionTestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('type', models.CharField(choices=[('AUDIO-TO-LOGOGRAM', 'Audio to Logogram'), ('LOGOGRAM-TO-AUDIO', 'Logogram to Audio'), ('LOGOGRAM-TO-MEANING', 'Logogram to Meaning'), ('LOGOGRAM-TO-PINYIN', 'Logogram to Pinyin'), ('MEANING-TO-LOGOGRAM', 'Meaning to Logogram'), ('PINYIN-TO-LOGOGRAM', 'Pinyin to Logogram')], max_length=32)),
                ('question', models.TextField()),
                ('alternatives', models.JSONField(default=list)),
                ('audio', models.CharField(blank=True, default='', max_length=512)),
                ('curr_answer', models.CharField(blank=True, choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D'), ('e', 'E')], max_length=1, null=True)),
                ('expected_answer', models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D'), ('e', 'E')], max_length=1)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='radicals.radicalsessiontest')),
            ],
            options={
                'ordering': ['test', 'number'],
                'constraints': [models.UniqueConstraint(fields=('test', 'number'), name='uniq_test_question_number')],
            },
        ),
        migrations.CreateModel(
            name='LogogramWordMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logogram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radicals.logogram')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radicals.word')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('word', 'logogram'), name='uniq_word_logogram')],
            },
        ),
        migrations.CreateModel(
            name='WordSentenceMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radicals.sentence')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radicals.word')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('sentence', 'word'), name='uniq_sentence_word')],
            },
        ),
    ]
