# Generated by Django 6.0.6 on 2026-06-25 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radicals', '0002_alter_radicalsessiontestquestion_curr_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='radicalsession',
            name='user',
        ),
        migrations.RemoveField(
            model_name='radicalsessiontest',
            name='session',
        ),
        migrations.RemoveConstraint(
            model_name='radicalsessionradical',
            name='uniq_session_radical',
        ),
        migrations.RemoveConstraint(
            model_name='radicalsessionradical',
            name='uniq_session_position',
        ),
        migrations.RemoveConstraint(
            model_name='radicalsessiontestquestion',
            name='uniq_test_question_number',
        ),
        migrations.RemoveField(
            model_name='radicalsessionradical',
            name='radical',
        ),
        migrations.RemoveField(
            model_name='radicalsessionradical',
            name='session',
        ),
        migrations.RemoveField(
            model_name='radicalsessiontestquestion',
            name='test',
        ),
        migrations.DeleteModel(
            name='RadicalSession',
        ),
        migrations.DeleteModel(
            name='RadicalSessionRadical',
        ),
        migrations.DeleteModel(
            name='RadicalSessionTest',
        ),
        migrations.DeleteModel(
            name='RadicalSessionTestQuestion',
        ),
    ]
