# Generated by Django 6.0.6 on 2026-06-26 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radicals', '0003_remove_radicalsession_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radical',
            name='meaning',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='radical',
            name='pinyin',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='radical',
            name='pronounce',
            field=models.CharField(max_length=512),
        ),
    ]
