# Generated by Django 6.0.6 on 2026-06-26 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radicals', '0004_alter_radical_meaning_alter_radical_pinyin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radicallogogrammap',
            name='radical',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='radical_logograms', to='radicals.radical'),
        ),
    ]
