# Generated by Django 6.0.6 on 2026-06-29 14:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('language_model', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SentenceSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('highest_score', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SentenceSessionSentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentence_sessions', to='language_model.sentence')),
                ('sentence_cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentencecluster_sessions', to='language_model.sentencecluster')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_sentences', to='sentence_sessions.sentencesession')),
            ],
            options={
                'ordering': ['session', 'position'],
                'constraints': [models.UniqueConstraint(fields=('session', 'sentence'), name='uniq_session_sentence'), models.UniqueConstraint(fields=('session', 'sentence_cluster'), name='uniq_session_sentence_cluster'), models.UniqueConstraint(fields=('session', 'position'), name='uniq_seq_session_position')],
            },
        ),
    ]
