# Generated by Django 6.0.6 on 2026-06-30 15:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('language_model', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentenceSessionSentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['session', 'position'],
            },
        ),
        migrations.CreateModel(
            name='SentenceSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('highest_score', models.PositiveIntegerField(default=0)),
                ('sentence_cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentencecluster_sessions', to='language_model.sentencecluster')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
