# Generated by Django 6.0.6 on 2026-06-28 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('language_model', '0001_initial'),
        ('sentence_sessions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sentencesession',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sentencesessionsentence',
            name='sentence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentence_sessions', to='language_model.sentence'),
        ),
        migrations.AddField(
            model_name='sentencesessionsentence',
            name='sentence_cluster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentencecluster_sessions', to='language_model.sentencecluster'),
        ),
        migrations.AddField(
            model_name='sentencesessionsentence',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_sentences', to='sentence_sessions.sentencesession'),
        ),
        migrations.AddConstraint(
            model_name='sentencesessionsentence',
            constraint=models.UniqueConstraint(fields=('session', 'sentence'), name='uniq_session_sentence'),
        ),
        migrations.AddConstraint(
            model_name='sentencesessionsentence',
            constraint=models.UniqueConstraint(fields=('session', 'sentence_cluster'), name='uniq_session_sentence_cluster'),
        ),
        migrations.AddConstraint(
            model_name='sentencesessionsentence',
            constraint=models.UniqueConstraint(fields=('session', 'position'), name='uniq_seq_session_position'),
        ),
    ]
