# Generated by Django 6.0.6 on 2026-06-25 12:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('radical_sessions', '0002_remove_radicalsessiontest_session_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RadicalSessionTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.PositiveIntegerField(default=0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='radical_sessions.radicalsession')),
            ],
            options={
                'ordering': ['-finished_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RadicalSessionTestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('type', models.CharField(choices=[('AUDIO-TO-LOGOGRAM', 'Audio to Logogram'), ('LOGOGRAM-TO-AUDIO', 'Logogram to Audio'), ('LOGOGRAM-TO-MEANING', 'Logogram to Meaning'), ('LOGOGRAM-TO-PINYIN', 'Logogram to Pinyin'), ('MEANING-TO-LOGOGRAM', 'Meaning to Logogram'), ('PINYIN-TO-LOGOGRAM', 'Pinyin to Logogram')], max_length=32)),
                ('question', models.TextField()),
                ('alternatives', models.JSONField(default=list)),
                ('audio', models.CharField(blank=True, default='', max_length=512)),
                ('curr_answer', models.CharField(blank=True, choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D'), ('e', 'E')], default='', max_length=1)),
                ('expected_answer', models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D'), ('e', 'E')], max_length=1)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='radical_tests.radicalsessiontest')),
            ],
            options={
                'ordering': ['test', 'number'],
                'constraints': [models.UniqueConstraint(fields=('test', 'number'), name='uniq_test_question_number')],
            },
        ),
    ]
