# Generated by Django 6.0.6 on 2026-06-30 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('practice_assessments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RadicalSessionAssessmentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('question', models.TextField()),
                ('audio', models.CharField(blank=True, default='', max_length=512)),
                ('curr_answer', models.CharField(blank=True, choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D'), ('e', 'E')], default='', max_length=1)),
                ('expected_answer', models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D'), ('e', 'E')], max_length=1)),
                ('type', models.CharField(choices=[('AUDIO-TO-LOGOGRAM', 'Audio to Logogram'), ('LOGOGRAM-TO-AUDIO', 'Logogram to Audio'), ('LOGOGRAM-TO-MEANING', 'Logogram to Meaning'), ('LOGOGRAM-TO-PINYIN', 'Logogram to Pinyin'), ('MEANING-TO-LOGOGRAM', 'Meaning to Logogram'), ('PINYIN-TO-LOGOGRAM', 'Pinyin to Logogram')], max_length=32)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='practice_assessments.radicalsessionassessment')),
            ],
            options={
                'ordering': ['assessment', 'number'],
            },
        ),
        migrations.CreateModel(
            name='RadicalSessionAssessmentQuestionAlt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D'), ('e', 'E')], max_length=1)),
                ('type', models.CharField(choices=[('AUDIO', 'Audio'), ('TEXT', 'Text')], max_length=255)),
                ('payload', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_alternatives', to='practice_questions.radicalsessionassessmentquestion')),
            ],
            options={
                'ordering': ['question', 'letter'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SentenceSessionAssessmentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('question', models.TextField()),
                ('audio', models.CharField(blank=True, default='', max_length=512)),
                ('curr_answer', models.CharField(blank=True, choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D'), ('e', 'E')], default='', max_length=1)),
                ('expected_answer', models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D'), ('e', 'E')], max_length=1)),
                ('type', models.CharField(choices=[('SENTENCE-AUDIO-TO-WORD-AUDIO', 'Sentence Audio to Word Audio'), ('SENTENCE-TEXT-TO-WORD-AUDIO', 'Sentence Text to Word Audio'), ('SENTENCE-AUDIO-TO-WORD-TEXT', 'Sentence Audio to Word Text'), ('SENTENCE-TEXT-TO-WORD-TEXT', 'Sentence Text to Word Text'), ('LOGOGRAM-TO-RADICALS', 'Logogram to Radicals')], max_length=32)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='practice_assessments.sentencesessionassessment')),
            ],
            options={
                'ordering': ['assessment', 'number'],
            },
        ),
        migrations.CreateModel(
            name='SentenceSessionAssessmentQuestionAlt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D'), ('e', 'E')], max_length=1)),
                ('type', models.CharField(choices=[('AUDIO', 'Audio'), ('TEXT', 'Text')], max_length=255)),
                ('payload', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_alternatives', to='practice_questions.sentencesessionassessmentquestion')),
            ],
            options={
                'ordering': ['question', 'letter'],
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='radicalsessionassessmentquestion',
            constraint=models.UniqueConstraint(fields=('assessment', 'number'), name='uniq_radical_assessment_question_number'),
        ),
        migrations.AddConstraint(
            model_name='radicalsessionassessmentquestionalt',
            constraint=models.UniqueConstraint(fields=('letter', 'question'), name='radical_uniq_letter_question'),
        ),
        migrations.AddConstraint(
            model_name='sentencesessionassessmentquestion',
            constraint=models.UniqueConstraint(fields=('assessment', 'number'), name='uniq_sentence_assessment_question_number'),
        ),
        migrations.AddConstraint(
            model_name='sentencesessionassessmentquestionalt',
            constraint=models.UniqueConstraint(fields=('letter', 'question'), name='sentence_uniq_letter_question'),
        ),
    ]
