# Generated by Django 6.0.6 on 2026-07-01 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedSpeech',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('audio', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Logogram',
            fields=[
                ('id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('occurrences', models.PositiveIntegerField(default=0)),
                ('pinyin', models.TextField()),
                ('meaning', models.TextField()),
                ('pronounce', models.CharField(blank=True, max_length=512)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Radical',
            fields=[
                ('id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('pinyin', models.TextField()),
                ('meaning', models.TextField()),
                ('pronounce', models.CharField(max_length=512)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('value', models.TextField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('output', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('value', models.TextField()),
                ('pronounce', models.CharField(blank=True, max_length=512)),
                ('pos_tag', models.CharField(max_length=255)),
                ('occurrences', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RadicalLogogramMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logogram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logogram_radicals', to='language_model.logogram')),
                ('radical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='radical_logograms', to='language_model.radical')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('logogram', 'radical'), name='uniq_logogram_radical')],
            },
        ),
        migrations.CreateModel(
            name='LogogramWordMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logogram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='language_model.logogram')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_logograms', to='language_model.word')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('word', 'logogram'), name='uniq_word_logogram')],
            },
        ),
        migrations.CreateModel(
            name='WordSentenceMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentence_words', to='language_model.sentence')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_sentences', to='language_model.word')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('sentence', 'word'), name='uniq_sentence_word')],
            },
        ),
    ]
