# Generated by Django 6.0.6 on 2026-07-01 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language_model', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaskedSentenceAudio',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('audio', models.FileField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='word',
            name='occurrences',
            field=models.PositiveIntegerField(),
        ),
    ]
