# Generated by Django 6.0.6 on 2026-07-01 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('language_model', '0002_maskedsentenceaudio_alter_word_occurrences'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MaskedSentenceAudio',
            new_name='GeneratedSpeech',
        ),
    ]
