# Generated by Django 6.0.6 on 2026-07-01 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language_model', '0003_rename_maskedsentenceaudio_generatedspeech'),
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('output', models.TextField()),
            ],
        ),
    ]
