# Generated by Django 6.0.6 on 2026-06-25 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radical_sessions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='radicalsessiontest',
            name='session',
        ),
        migrations.RemoveConstraint(
            model_name='radicalsessiontestquestion',
            name='uniq_test_question_number',
        ),
        migrations.RemoveField(
            model_name='radicalsessiontestquestion',
            name='test',
        ),
        migrations.DeleteModel(
            name='RadicalSessionTest',
        ),
        migrations.DeleteModel(
            name='RadicalSessionTestQuestion',
        ),
    ]
