# Generated by Django 6.0.6 on 2026-06-28 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('language_model', '0001_initial'),
        ('radical_sessions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='radicalsession',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='radicalsessionradical',
            name='radical',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='radical_sessions', to='language_model.radical'),
        ),
        migrations.AddField(
            model_name='radicalsessionradical',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_radicals', to='radical_sessions.radicalsession'),
        ),
        migrations.AddConstraint(
            model_name='radicalsessionradical',
            constraint=models.UniqueConstraint(fields=('session', 'radical'), name='uniq_session_radical'),
        ),
        migrations.AddConstraint(
            model_name='radicalsessionradical',
            constraint=models.UniqueConstraint(fields=('session', 'position'), name='uniq_radical_session_position'),
        ),
    ]
