# Generated by Django 6.0.6 on 2026-06-26 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radical_sessions', '0002_remove_radicalsessiontest_session_and_more'),
        ('radicals', '0005_alter_radicallogogrammap_radical'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radicalsessionradical',
            name='radical',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='radical_sessions', to='radicals.radical'),
        ),
    ]
